guests=['Marilyn', 'Kate', 'Diana'] 
print ((guests[0]) + " kindly join me for dinner.")
print ((guests[1]) + " kindly join me for dinner.")
print ((guests[2]) + " kindly join me for dinner.")
print ('\n' + (guests[0]) + " can't make it to dinner.")
del(guests[0])
guests.insert(0, 'Elizabeth')
print ('\n' + (guests[0]) + " kindly join me for dinner.")
print ((guests[1]) + " kindly join me for dinner.")
print ((guests[2]) + " kindly join me for dinner.")
print ("\nSorry, I can only invite two people.")
print ("Sorry,"+ (guests[0])+ " I can only invite 2 people")
guests.pop(0)
print ('\n' + (guests[0]) + " kindly join me for dinner.")
print ((guests[1]) + " kindly join me for dinner.")
del(guests[0])
del(guests[0])
print (guests)