places= ['Japan','Maldives','Canada','Turkey','South Korea']
print (places)
print("\nAlphabetical:")
print(sorted(places))
print (places)
print("\nReverse Alphabetical:")
print(sorted(places, reverse=True))
print (places)
print("\nReverse:")
places.reverse()
print(places)
print("\nOriginal Order:")
places.reverse()
print(places)
print("\nAlphabetical")
places.sort()
print(places)
print("\nReverse Alphabetical")
places.sort(reverse=True)
print(places)