guests=['Marilyn', 'Kate', 'Diana'] 
print ((guests[0]) + " kindly join me for dinner.")
print ((guests[1]) + " kindly join me for dinner.")
print ((guests[2]) + " kindly join me for dinner.")
print ((guests[0]) + " can't make it to dinner.")
del(guests[1])
guests.insert(0, 'Elizabeth')
print ((guests[0]) + " kindly join me for dinner.")
print ((guests[1]) + " kindly join me for dinner.")
print ((guests[2]) + " kindly join me for dinner.")